### ISSUE TITLE
[Design Issue] Consistent designs/content for budget tables are needed

### ISSUE THREAD

**Issue by beparticular** [Enterprise-CMCS/eAPD#3380] opened 2021-08-05 17:30 UTC
Spin off from #3148 
"Just a note about the "Budget and FFP tables" - it would be a nice to have to include this because it would help orient the reviewer where they are in the export. The Builder view is less concerning because at least the side nav can help remind the user which Activity they are working in, but if it's easier to implement the change all at one, I'm not opposed to it."

Some of our tables have the Activity Name in the headers (proposed budget) and some don't (FFP and Budget within an activity). We do however add the activity number into the ffp and budget table headers. 
Noticing this led us to think it might be a good idea to try and bring the table designs more into alignment. There is an issue out for this #2150, but we should determine through the work on the design ticket, how much alignment do we need at this time. Is it just names, or should we do more. 

### This task is done when…

- [x] first determine what the scope of this issue is vs #2150
- [x] Review/List of all Budget/FFP tables that will be in the MMIS IAPD
- [x] Assessment of tables to ensure consistency/readability (from the description, in both the builder and export views)
- [x] See which ones need to change or be updated (or if not designed yet, which ones still need to be designed); ID which ones need to be updated now or what we can hold off on
- [x] Document table design (maybe something like the validation page)?
- [x] designs are created, taking into consideration multiple FFY, multiple entries, long entries, weird entries, and/or the export view if applicable + validation 
- [x] 508 considerations and/or recommendations are reviewed
- [x] designs are shared
- [ ] designs are approved by product

**Comment by jeromeleecms** [comment] 2022-11-16 18:44
For MMIS rollout:
1) Review/List of all Budget/FFP tables that will be in the MMIS IAPD
2) Assessment of tables to ensure consistency/readability (from the description, in both the builder and export views)
3) See which ones need to change or be updated (or if not designed yet, which ones still need to be designed); ID which ones need to be updated now or what we can hold off on
4) Document table design (maybe something like the validation page)?

How's that @akuas? We can narrow the scope if needed as well.

**Comment by akuas** [comment] 2022-11-16 19:02
@jeromeleecms That clarifies things. Thanks, I'll add this to the acceptance criteria.

**Comment by akuas** [comment] 2022-11-21 12:38
List of MMIS Tables
1. Results of Previous Activities: Actual Expenditures with Grand Totals
2. Cost Allocation and Other Funding: Other Funding Amount: Activity Total Cost
3. Budget and FFP: Activity X Budget for FFY X
4. Budget and FFP: Total Computable Medicaid Cost
5. Budget and FFP: Estimated Quarterly Expenditure
6. Activity Schedule Summary: Schedule Summary by Activity
7. Activity Schedule Summary: Milestone Tables by Activity
8. Proposed Budget: Combined Activity Costs
9. Proposed Budget: State and Contractor Costs Breakdown (formerly known as Activity Breakdown)
10. Proposed Budget: Summary Budget Table
11. Executive Summary: Program Budget Table

**Comment by akuas** [comment] 2022-11-29 21:36
Proposed Design Improvements
1. Make the table headers consistent and more prominent
2. Increase the color contrast of the the gray rows
3. Possibly replace the gray header row with our blue primary color
4. We need to be clearer what the total means and if the number flows into any other calculation. In some cases a hint text would be needed to explain how the total was calculated
5. Change the alignment of text in the table to be left aligned so that it is easier to read
6. Use alternating row colors
7. Be specific when things are subtotals vs totals

**Comment by akuas** [comment] 2022-12-13 15:04
Below is the table redesign with an updated list of changes in the annotations. @jeromeleecms 
https://www.figma.com/file/hJpKHKU6fz5J0Z7fisSwa2/eAPD-MMIS-2022?node-id=2779%3A17295&t=xVPoUarw3tJ2DiIJ-1

**Comment by jeromeleecms** [comment] 2022-12-13 17:32
Added some general thoughts/comments. I like the direction this is going! Can we review together so I can understand some of the justifications/thoughts behind some of the decisions?

**Comment by akuas** [comment] 2022-12-19 19:43
@stephanieboydcms Can you please review this ticket and let me know what you think?

**Comment by stephanieboydcms** [comment] 2022-12-19 20:28
@akuas these look REALLY good!  I made some comments in Figma.  Let me know if you would like to discuss any of them further!

**Comment by akuas** [comment] 2022-12-27 17:49
Closing Notes as of December 27th 2022 (in progress)
### 1. Add help text explaining the table content and calculations, when needed.
> This only applies to the Summary Budget Table, at the moment. We need to better explain how the #sare generated and from what part of the builder are they coming from.
### 2. Add alternating rows to large data sets
> To improve scanability, I think we need alternating rows for tables with 5 or more 
rows. It will help users follow the content across a row better. It is however not beneficial for smaller datasets because there is less of an issue with scanning and alternating rows, may give off the impression that we are highlighting some information and not others. From a dev perspective, we need a way to conditionally add alt rows if rows are greater
than 4 Even numbers would have the #F1F1F1 background color.
### 3. Highlight totals
> We are already doing this but we can also highlight subtotals but we can highlight subtotal columns to enhance scanability. This applies to:
>> - Other Funding amount : Activity total cost table
>> - Proposed Budget: Combined Activity Cost table
>> - Proposed Budget: State and Contractor Cost breakdown table
>> - Proposed Budget: Summary Budget Table
>> - Budget and FFP table
>> - Executive Summary Table
### 4. Make the tables more visually consistent
> Most table headers have the gray background and the black text with the exception of proposed budget table, activity schedule summary tables so we should change those to maintain consistency.Another reason for the change is that it looks closer to the CMS design system and it is less jarring color contrast
### 5. Left align columns
> Generally tables are left aligned because it fits with users experience with reading left to right, so that is what motivated this change. But if it is a big lift we could hold off on this change.

**Comment by akuas** [comment] 2023-01-10 16:46
@jeromeleecms @stephanieboydcms @SGilliamA1M This ticket is ready for final review.

**Comment by akuas** [comment] 2023-01-17 17:24
@thetif Good morning Tif, so I concluded that the lighter yellow works in most cases to highlight the subtotal. The black text can be read against the light yellow. The issue is for the alternating rows, the yellow background color row next to the alternating gray row background color, so Im using this dark blue text color to highlight the subtotal when there are alternating rows. If there are no alt rows, we can keep the tables as is. Please let me know what you think.
https://www.figma.com/file/hJpKHKU6fz5J0Z7fisSwa2/eAPD-MMIS-2022?node-id=3380%3A19695&t=xsTGAV3Qzv7JpWJj-1

**Comment by SGilliamA1M** [comment] 2023-01-17 17:31
@akuas table changes are clean and consistent, well done! Also includes updates from our previous Design Sync.

**Comment by akuas** [comment] 2023-01-18 22:47
@jeromeleecms This ticket is ready to review. I updated the proposed budget subtotals by removing the background color and changing the text color. I was wondering if you knew, if we are conveying the message that a row is a subtotal through the copy and applying bold to the text, does it matter if the gray next to the light yellow fail the color contrast?

https://www.figma.com/file/hJpKHKU6fz5J0Z7fisSwa2/eAPD-MMIS-2022?node-id=2779%3A17295&t=89pFL0KQEBAIq7x9-1

**Comment by jeromeleecms** [comment] 2023-01-19 00:20
Will take a look - the WCAG guidance on contrast ratios between text / background colors: https://www.w3.org/WAI/WCAG21/Understanding/contrast-minimum.html

From what I'm reading, if the font size if 14 point + bold and the contract ratio is 3:1 we are are AA compliance. From the website:

Situation B: text is at least 18 point if not bold and at least 14 point if bold
[G145: Ensuring that a contrast ratio of at least 3:1 exists between text (and images of text) and background behind the text](https://www.w3.org/WAI/WCAG21/Techniques/general/G145)
[G148: Not specifying background color, not specifying text color, and not using technology features that change those defaults](https://www.w3.org/WAI/WCAG21/Techniques/general/G148)
[G174: Providing a control with a sufficient contrast ratio that allows users to switch to a presentation that uses sufficient contrast](https://www.w3.org/WAI/WCAG21/Techniques/general/G174)

**Comment by jeromeleecms** [comment] 2023-01-19 22:46
Overall looking great - just a few clarifying questions/comments on the use of the "subtotal yellow" vs. the "Grand Total / Total Computable" use.

**Comment by stephanieboydcms** [comment] 2023-01-20 15:52
Just one quick comment for clarity on Figma.  Amazing job!

**Comment by jeromeleecms** [comment] 2023-01-30 17:10
@stephanieboydcms anything else on this one before we transition to Dev?

**Comment by stephanieboydcms** [comment] 2023-01-30 17:18
I am good @jeromeleecms to push this Dev.  THanks!

**Comment by thetif** [comment] 2023-02-01 21:40
created dev ticket #4506

**Comment by jeromeleecms** [comment] 2023-02-02 23:45
The Dev issue looks good. Closing design ticket.

**Closed by jeromeleecms** 2023-02-02 23:45 UTC
Labels: Design, extra large
